import type { ShaderGradientParams } from "./ShaderGradientVariantBackground";

/**
 * Presets ShaderGradient pour la galerie Mist Vtensor.
 *
 * 11 variantes pour comparer types (waterPlane / plane / sphere), palettes,
 * vitesses, densités. À utiliser avec `<ShaderGradientVariantBackground>`.
 */
export type MistPreset = {
  id: string;
  name: string;
  description: string;
  params: ShaderGradientParams;
};

export const SHADER_MIST_PRESETS: MistPreset[] = [
  {
    id: "shader-mist-premium",
    name: "Mist Premium",
    description: "Base premium calme, palette Vtensor, mist lent.",
    params: {
      type: "waterPlane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.15,
      uStrength: 2,
      uDensity: 1.2,
      cPolarAngle: 120,
      grain: "on",
    },
  },
  {
    id: "shader-mist-wave-plane",
    name: "Wave Plane",
    description: "Plan ondulant, vue de face, fréquence moyenne.",
    params: {
      type: "plane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.2,
      uStrength: 1.5,
      uFrequency: 2.5,
      cAzimuthAngle: 180,
      cPolarAngle: 90,
      grain: "on",
    },
  },
  {
    id: "shader-mist-liquid-sphere",
    name: "Liquid Sphere",
    description: "Sphère liquide vue centrée, distorsion forte.",
    params: {
      type: "sphere",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.1,
      uStrength: 2.5,
      uFrequency: 4,
      cDistance: 4,
      grain: "on",
    },
  },
  {
    id: "shader-mist-dynamic",
    name: "Dynamic Mist",
    description: "Mist plus rapide et dense, énergique.",
    params: {
      type: "waterPlane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.4,
      uStrength: 3,
      uDensity: 1.5,
      cPolarAngle: 120,
      grain: "on",
    },
  },
  {
    id: "shader-mist-soft",
    name: "Soft Mist",
    description: "Mist très doux, brightness élevée, presque immobile.",
    params: {
      type: "waterPlane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.08,
      uStrength: 1,
      uDensity: 0.8,
      brightness: 1.4,
      cPolarAngle: 120,
      grain: "on",
    },
  },
  {
    id: "shader-mist-aurora",
    name: "Aurora-like Plane",
    description: "Palette aurore élargie violet/cyan/bleu, plan tilted.",
    params: {
      type: "plane",
      color1: "#7C3AED",
      color2: "#22D3EE",
      color3: "#0EA5E9",
      uSpeed: 0.18,
      uStrength: 2,
      cPolarAngle: 150,
      grain: "on",
    },
  },
  {
    id: "shader-mist-cyan",
    name: "Cyan Mist",
    description: "Cyan dominant, plus tech/froid.",
    params: {
      type: "waterPlane",
      color1: "#06B6D4",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.2,
      uStrength: 2.2,
      uDensity: 1.2,
      cPolarAngle: 120,
      grain: "on",
    },
  },
  {
    id: "shader-mist-violet-deep",
    name: "Violet Deep",
    description: "Violet profond mono-chromatique, sans cyan.",
    params: {
      type: "waterPlane",
      color1: "#7C3AED",
      color2: "#A78BFA",
      color3: "#1E0A2E",
      uSpeed: 0.15,
      uStrength: 2.2,
      uDensity: 1.2,
      cPolarAngle: 120,
      bgColor: "#1E0A2E",
      grain: "on",
    },
  },
  {
    id: "shader-mist-tilted-sphere",
    name: "Tilted Sphere",
    description: "Sphère vue d'angle, distance proche.",
    params: {
      type: "sphere",
      color1: "#7C3AED",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.12,
      uStrength: 2,
      cAzimuthAngle: 170,
      cPolarAngle: 90,
      cDistance: 3.6,
      grain: "on",
    },
  },
  {
    id: "shader-mist-slow-drift",
    name: "Slow Drift",
    description: "Dérive très lente, contemplative, idéale Hero statique.",
    params: {
      type: "waterPlane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.05,
      uStrength: 2,
      uDensity: 1,
      uFrequency: 2,
      cPolarAngle: 120,
      grain: "on",
    },
  },
  {
    id: "shader-mist-storm",
    name: "High Density Storm",
    description: "Tempête dense, très dynamique, beaucoup de mouvement.",
    params: {
      type: "waterPlane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.5,
      uStrength: 4,
      uDensity: 2,
      uFrequency: 4,
      cPolarAngle: 120,
      grain: "on",
    },
  },
  {
    id: "shader-mist-minimal",
    name: "Minimal Mist",
    description: "Très épuré, pas de grain, brightness élevée.",
    params: {
      type: "waterPlane",
      color1: "#8B5CF6",
      color2: "#22D3EE",
      color3: "#0A0A0F",
      uSpeed: 0.12,
      uStrength: 1,
      uDensity: 0.7,
      brightness: 1.4,
      grain: "off",
      cPolarAngle: 120,
    },
  },
];
